---
- hosts: all
  vars:
    basedir: "/run/media/db5/backup/mm/db5/"
  tasks:

    - name: find all files
      shell: find /run/media/db5/backup/mm/db5/people_east/marcella-2/ -type f
      register: allfilenames

    - name: clean up file manes
      shell: "mv '{{ item }}' $(echo '{{ item }}'  | sed -e 's/[^a-zA-Z0-9/_.-]/_/g') || true"
      with_items: "{{ allfilenames.stdout_lines }}"


    # - name: clean up file manes
    #   shell: "echo '{{ item }}' | sed -e 's/[^a-zA-Z0-9/_.-]/_/g' >> /tmp/renaming.txt"
    #   with_items: "{{ allfilenames.stdout_lines }}"

    - name: "clean up old cats"
      file:
        state: absent
        path: "~/.local/share/gthumb/catalogs/"

    - name: "create directory"
      file:
        path: "~/.local/share/gthumb/catalogs/"
        state: directory

### collacting all used cats ###

    - name: "create ./find_all_tags.sh"
      template:
        src: "./templates/find_all_tags_template.sh"
        dest: "/tmp/find_all_tags.sh"

    - file:
        path: /tmp/find_all_tags.sh
        mode: 0777

    - name: "creat find all cats"
      shell: /tmp/find_all_tags.sh
      register: list_off_all_tags

    - debug:
        msg: "{{ list_off_all_tags.stdout }}"

    - debug:
        msg: "{{ list_off_all_tags.stdout_lines }}"

### Update tag file ###

    - name: "create unknown_cats.search"
      template:
        src: "./templates/tags-teamplate.xml"
        dest: "~/.config/gthumb/tags.xml"

### ALL CAT TAGS ###

    - name: "creat allcats vars"
      shell: /tmp/find_all_tags.sh | grep  '^c-'
      register: allcats

    - debug:
        msg: "{{ allcats.stdout_lines }}"

    - name: "create directory catalogs/tags"
      file:
        path: "~/.local/share/gthumb/catalogs/tags"
        state: directory

    - name: "copy temlptas tags"
      template:
        src: "./templates/cat-template.search"
        dest: "~/.local/share/gthumb/catalogs/tags/{{ item }}.search"
      with_items: "{{ allcats.stdout_lines }}"
      delegate_to: localhost

    - name: "replace key word"
      replace:
        path: "~/.local/share/gthumb/catalogs/tags/{{ item }}.search"
        regexp: 'tage_name'
        replace: "{{ item }}"
      with_items: "{{ allcats.stdout_lines }}"
      delegate_to: localhost


### ALL PERSON TAGS ###

    - name: "creat allperson vars"
      shell: /tmp/find_all_tags.sh | grep  '^p_'
      register: allperson

    - debug:
        msg: "{{ allperson.stdout_lines }}"

    - name: "create directory catalogs/person"
      file:
        path: "~/.local/share/gthumb/catalogs/person"
        state: directory

    - name: "copy temlptas person"
      template:
        src: "./templates/cat-template.search"
        dest: "~/.local/share/gthumb/catalogs/person/{{ item }}.search"
      with_items: "{{ allperson.stdout_lines }}"
      delegate_to: localhost

    - name: "replace key word"
      replace:
        path: "~/.local/share/gthumb/catalogs/person/{{ item }}.search"
        regexp: 'tage_name'
        replace: "{{ item }}"
      with_items: "{{ allperson.stdout_lines }}"
      delegate_to: localhost

### ALL names TAGS ###

    - name: "creat allnames vars"
      shell: /tmp/find_all_tags.sh | grep  '^y-'
      register: allnames

    - debug:
        msg: "{{ allnames.stdout_lines }}"

    - name: "create directory catalogs/names"
      file:
        path: "~/.local/share/gthumb/catalogs/names"
        state: directory

    - name: "copy temlptas tags"
      template:
        src: "./templates/cat-template.search"
        dest: "~/.local/share/gthumb/catalogs/names/{{ item }}.search"
      with_items: "{{ allnames.stdout_lines }}"
      delegate_to: localhost

    - name: "replace key word"
      replace:
        path: "~/.local/share/gthumb/catalogs/names/{{ item }}.search"
        regexp: 'tage_name'
        replace: "{{ item }}"
      with_items: "{{ allnames.stdout_lines }}"
      delegate_to: localhost

### ALL nationality TAGS ###

    - name: "creat nationality vars"
      shell: /tmp/find_all_tags.sh | grep  '^n-'
      register: nationality

    - debug:
        msg: "{{ nationality.stdout_lines }}"

    - name: "create directory catalogs/names"
      file:
        path: "~/.local/share/gthumb/catalogs/nationality"
        state: directory

    - name: "copy temlptas tags"
      template:
        src: "./templates/cat-template.search"
        dest: "~/.local/share/gthumb/catalogs/nationality/{{ item }}.search"
      with_items: "{{ nationality.stdout_lines }}"
      delegate_to: localhost

    - name: "replace key word"
      replace:
        path: "~/.local/share/gthumb/catalogs/nationality/{{ item }}.search"
        regexp: 'tage_name'
        replace: "{{ item }}"
      with_items: "{{ nationality.stdout_lines }}"
      delegate_to: localhost


### ALL style TAGS ###

    - name: "creat style vars"
      shell: /tmp/find_all_tags.sh | grep  '^s-'
      register: style

    - debug:
        msg: "{{ style.stdout_lines }}"

    - name: "create directory catalogs/names"
      file:
        path: "~/.local/share/gthumb/catalogs/style"
        state: directory

    - name: "copy temlptas tags"
      template:
        src: "./templates/cat-template.search"
        dest: "~/.local/share/gthumb/catalogs/style/{{ item }}.search"
      with_items: "{{ style.stdout_lines }}"
      delegate_to: localhost

    - name: "replace key word"
      replace:
        path: "~/.local/share/gthumb/catalogs/style/{{ item }}.search"
        regexp: 'tage_name'
        replace: "{{ item }}"
      with_items: "{{ style.stdout_lines }}"
      delegate_to: localhost

#### NONPREFIX ####
    - name: "create directory"
      file:
        path: "~/.local/share/gthumb/catalogs/nonprefix"
        state: directory

    - name: "creat nonyear vars"
      shell: /tmp/find_all_tags.sh | grep -v '^y-'  | grep -v '^c-' | grep -v '^p_' | grep -v '^n-'  | grep -v '^s-'
      register: nonprefix

    - debug:
        msg: "{{ nonprefix.stdout_lines }}"


    - name: "copy temlptas"
      template:
        src: "./templates/cat-template.search"
        dest: "~/.local/share/gthumb/catalogs/nonprefix/{{ item }}.search"
      with_items: "{{ nonprefix.stdout_lines }}"
      delegate_to: localhost

    - ame: "replace key word"
      replace:
        path: "~/.local/share/gthumb/catalogs/nonprefix/{{ item }}.search"
        regexp: 'tage_name'
        replace: "{{ item }}"
      with_items: "{{ nonprefix.stdout_lines }}"
      delegate_to: localhost

### UNKNOW ###

    - name: "create unknown_cats.search"
      template:
        src: "./templates/unknown-template.search"
        dest: "~/.local/share/gthumb/catalogs/unknown-cats.search"
