---
- hosts: all
  roles:
#    - delete_abandoned_comments
    - cleanup_filenames
    - delete_catalogs
    - create_find_all_tags
    # - collacting_alltags
    # - uncategorized_search
    # - collacting_category
    # - collacting_person
    # - collacting_name
    # - collacting_nationality
    # - collacting_style
