---
- hosts: all
  vars:
    basedir: "/home/or-master/a-z/b/bilder"
  tasks:

    - name: "clean up old cats"
      file:
        state: absent
        path: "~/.local/share/gthumb/catalogs/"

    - name: "create directory"
      file:
        path: "~/.local/share/gthumb/catalogs/"
        state: directory

### collacting all used cats ###

    - name: "create ./find_all_tags.sh"
      template:
        src: "./templates/find_all_tags_template.sh"
        dest: "/tmp/find_all_tags.sh"

    - file:
        path: /tmp/find_all_tags.sh
        mode: 0777

    - name: "creat find all cats"
      shell: /tmp/find_all_tags.sh
      register: list_off_all_tags

    - debug:
        msg: "{{ list_off_all_tags.stdout }}"

    - debug:
        msg: "{{ list_off_all_tags.stdout_lines }}"

### ALL YEAR TAGS ###

    - name: "creat allyear vars"
      shell: /tmp/find_all_tags.sh | grep  '^[0-9][0-9][0-9][0-9]'
      register: allyear

    - debug:
        msg: "{{ allyear.stdout_lines }}"

    - name: "create directory"
      file:
        path: "~/.local/share/gthumb/catalogs/year"
        state: directory

    - name: "copy temlptas"
      template:
        src: "./templates/cat-template.search"
        dest: "~/.local/share/gthumb/catalogs/year/{{ item }}.search"
      with_items: "{{ allyear.stdout_lines }}"
      delegate_to: localhost

    - name: "replace key word"
      replace:
        path: "~/.local/share/gthumb/catalogs/year/{{ item }}.search"
        regexp: 'tage_name'
        replace: "{{ item }}"
      with_items: "{{ allyear.stdout_lines }}"
      delegate_to: localhost


### UNKNOW ###

    - name: "create unknown_year.search"
      template:
        src: "./templates/unknown-year-template.search"
        dest: "~/.local/share/gthumb/catalogs/unknown-year.search"

    - name: "create unknown_cats.search"
      template:
        src: "./templates/unknown-template.search"
        dest: "~/.local/share/gthumb/catalogs/unknown-cats.search"


#### NONYEARS ####
    - name: "create directory"
      file:
        path: "~/.local/share/gthumb/catalogs/tags"
        state: directory

    - name: "creat nonyear vars"
      shell: /tmp/find_all_tags.sh | grep -v '^[0-9][0-9][0-9][0-9]'
      register: nonyear

    - debug:
        msg: "{{ nonyear.stdout_lines }}"


    - name: "copy temlptas"
      template:
        src: "./templates/cat-template.search"
        dest: "~/.local/share/gthumb/catalogs/tags/{{ item }}.search"
      with_items: "{{ nonyear.stdout_lines }}"
      delegate_to: localhost

    - ame: "replace key word"
      replace:
        path: "~/.local/share/gthumb/catalogs/tags/{{ item }}.search"
        regexp: 'tage_name'
        replace: "{{ item }}"
      with_items: "{{ nonyear.stdout_lines }}"
      delegate_to: localhost
