---
- hosts: all
  roles:
#    - cleanup_filenames
    - delete_abandoned_comments
    - delete_catalogs
    - create_find_all_tags
    - collecting_alltags
    - uncategorized_search
    - collecting_category
    - collecting_feature
    - collecting_name
    - collecting_nationality
    - collecting_nonprefix
    - collecting_person
    - collecting_style
