---
- hosts: all
  roles:
#    - cleanup_filenames
    - delete_abandoned_comments
    - delete_catalogs
    - create_find_all_tags
    - collacting_alltags
    - uncategorized_search
    - collacting_category
    - collacting_feature
    - collacting_name
    - collacting_nationality
    - collacting_nonprefix
    - collacting_person
    - collacting_style
