---
#### NONPREFIX ####
- name: "create directory"
  file:
    path: "~/.local/share/gthumb/catalogs/nonprefix"
    state: directory

- name: "creat nonprefix vars"
  shell: "{{ find_all_tags }} | grep -v '^y-' | grep -v '^c-' | grep -v '^p-' | grep -v '^n-' | grep -v '^s-' | grep -v '^f-'"
  register: nonprefix

- debug:
    msg: "{{ nonprefix.stdout_lines }}"


- name: "copy temlptas"
  template:
    src: "./templates/cat-template.search"
    dest: "~/.local/share/gthumb/catalogs/nonprefix/{{ item }}.search"
  with_items: "{{ nonprefix.stdout_lines }}"
  delegate_to: localhost

- name: "replace key word"
  replace:
    path: "~/.local/share/gthumb/catalogs/nonprefix/{{ item }}.search"
    regexp: 'tage_name'
    replace: "{{ item }}"
  with_items: "{{ nonprefix.stdout_lines }}"
  delegate_to: localhost
