---


- name: "find all orign files"
  shell: find {{ basedir }} -name '*.xml'
  register: allcomments

# - name: "create /tmp/double_check.sh"
#   template:
#     src: "../templates/double_check-template.sh"
#     dest: "/tmp/double_check.sh"

- name: "create /tmp/find_abandoned_comments.sh"
  template:
    src: "../templates/find_abandoned_comments-template.sh"
    dest: "/tmp/find_abandoned_comments.sh"

- name: "find all abandoned comments"
  shell: "bash /tmp/find_abandoned_comments.sh"
  register: all_abandoned_comments

- debug:
    msg: "{{ all_abandoned_comments.stdout_lines }}"

- name: "delede /tmp/find_abandoned_comments.sh"
  file:
    path: /tmp/find_abandoned_comments.sh
    state: absent


- name: "delede abandoned comments"
  file:
    path: rm {{ item }}
    state: absent
  with_items: "{{ all_abandoned_comments.stdout_lines }}"
