---


- name: "find all orign files"
  shell: find {{ basedir }} -name '*.xml'
  register: allcomments

# - name: "create /tmp/double_check.sh"
#   template:
#     src: "../templates/double_check-template.sh"
#     dest: "/tmp/double_check.sh"

- name: "create {{ find_abandoned_comments }}"
  template:
    src: "../templates/find_abandoned_comments-template.sh"
    dest: "{{ find_abandoned_comments }}"

- name: "find all abandoned comments"
  shell: "bash {{ find_abandoned_comments }}"
  register: all_abandoned_comments

- debug:
    msg: "{{ all_abandoned_comments.stdout_lines }}"

- name: "delede abandoned comments"
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ all_abandoned_comments.stdout_lines }}"
